WIFI_ROM_PATH ?= middleware/MTK/wifi_stack/rom/e2

#################################################################################
#include path
CFLAGS  += -I$(SOURCE_DIR)/$(WIFI_ROM_PATH)/hal/inc
CFLAGS  += -I$(SOURCE_DIR)/$(WIFI_ROM_PATH)/hal/inc/pse
CFLAGS  += -I$(SOURCE_DIR)/$(WIFI_ROM_PATH)/hal/inc/nic
CFLAGS  += -I$(SOURCE_DIR)/$(WIFI_ROM_PATH)/hal/inc/mgmt
CFLAGS  += -I$(SOURCE_DIR)/$(WIFI_ROM_PATH)/fw/inc
#################################################################################


#IOT Defines

CFLAGS += -DRT2860  -DWMM_SUPPORT
CFLAGS += -DCONFIG_STA_SUPPORT
#CFLAGS += -DWPA_SUPPLICANT_SUPPORT
CFLAGS += -DCONFIG_ROMSECTION_SUPPORT
#CFLAGS += -DCONFIG_RALINK_RT3052
CFLAGS += -DCONFIG_WPAPSK_DRIVER_SUPPORT
#CFLAGS += -DWSC_STA_SUPPORT
#CFLAGS += -DWSC_V2_SUPPORT
CFLAGS += -DAP_STARTUP
CFLAGS += -DCONFIG_AP_SUPPORT
CFLAGS += -DWSC_FEATURE_SUPPORT
CFLAGS += -DAPCLI_SUPPORT
#CFLAGS += -DMAC_REPEATER_SUPPORT
CFLAGS += -DMAT_SUPPORT
CFLAGS += -DDOT11N_DRAFT3
CFLAGS += -DIOT_WMM
CFLAGS += -DIOT_DEBUG_PRINT
CFLAGS += -DIOT_HOST_PRESENT
CFLAGS += -DIOT_SECURITY_SUPPORT
#CFLAGS += -DIOT_CFG80211_SUPPORT
CFLAGS += -DIOT_PROMISCUS_MODE
CFLAGS += -DIOT_WOW_SUPPORT
CFLAGS += -DIOT_OFFLOAD_ROUTINE
CFLAGS += -DIOT_POWER_SAVE
CFLAGS += -DDATA_PATH_87
CFLAGS += -DINBAND_MT7687
CFLAGS += -DN9_HAL_PORTING_UNPATCH
CFLAGS += -DBSS_STRUCTURE_CLEANUP
CFLAGS += -DUNPATCH_N9_PATCHES
#CFLAGS += -DDATA_PATH_86
CFLAGS += -DMT7686_BEACON_SUPPORT
CFLAGS += -DMT7687_BEACON_SUPPORT
CFLAGS += -DNEW_QUEUE_DESIGN
CFLAGS += -DSEND_DIRECLY_TO_LMAC
CFLAGS += -DPHYMODE_TO_WDEV
#CFLAGS += -DIOT_PROCESS_PORTING
CFLAGS += -DBCN_SYNCED_FROM_JEDI
#CFLAGS += -Werror
CFLAGS  += -Os # -O0 ==> change to -Os to save space
