/*
 * Generated by MTK Easy PinMux Tool Version 2.0.1 for 2523. Copyright MediaTek Inc. (C) 2015.
 * 2017-07-07 12:03:37:0746
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

const char BSP_HP_ANA_SW_PIN = 2;
const char BSP_HP_ANA_SW_PIN_M_GPIO = 0;
const char BSP_HP_ANA_SW_PIN_M_EINT = 1;
const char BSP_HP_ANA_SW_PIN_M_AUXADCIN_2 = 2;
const char BSP_HP_ANA_SW_PIN_M_U3RXD = 3;
const char BSP_HP_ANA_SW_PIN_M_U0CTS = 4;
const char BSP_HP_ANA_SW_PIN_M_MA_SPI1_A_MOSI = 5;
const char BSP_HP_ANA_SW_PIN_M_MA_EDIWS = 6;
const char BSP_HP_ANA_SW_PIN_M_MA_SPI0_A_MOSI = 7;
const char BSP_HP_ANA_SW_PIN_M_DEBUGMON13 = 8;
const char BSP_HP_ANA_SW_PIN_M_BT_BUCK_EN_HW = 9;


const char BSP_LED0_PIN = 14;
const char BSP_LED0_PIN_M_GPIO = 0;
const char BSP_LED0_PIN_M_EINT = 1;
const char BSP_LED0_PIN_M_CLKO = 2;
const char BSP_LED0_PIN_M_MA_EDICK = 3;
const char BSP_LED0_PIN_M_MA_SPI1_B_MISO = 4;
const char BSP_LED0_PIN_M_PWM3 = 5;
const char BSP_LED0_PIN_M_SLA_EDICK = 6;


const char HAL_KEYPAD_COL1_PIN = 19;
const char HAL_KEYPAD_COL1_PIN_M_GPIO = 0;
const char HAL_KEYPAD_COL1_PIN_M_KCOL1 = 1;
const char HAL_KEYPAD_COL1_PIN_M_EINT = 2;
const char HAL_KEYPAD_COL1_PIN_M_U0RTS = 3;
const char HAL_KEYPAD_COL1_PIN_M_SCL2 = 4;
const char HAL_KEYPAD_COL1_PIN_M_TRACEDATA1 = 5;
const char HAL_KEYPAD_COL1_PIN_M_DEBUGMON2 = 7;
const char HAL_KEYPAD_COL1_PIN_M_JTMS = 8;
const char HAL_KEYPAD_COL1_PIN_M_BTJTMS = 9;


const char HAL_KEYPAD_COL0_PIN = 20;
const char HAL_KEYPAD_COL0_PIN_M_GPIO = 0;
const char HAL_KEYPAD_COL0_PIN_M_KCOL0 = 1;
const char HAL_KEYPAD_COL0_PIN_M_GPSFSYNC = 2;
const char HAL_KEYPAD_COL0_PIN_M_U0CTS = 3;
const char HAL_KEYPAD_COL0_PIN_M_SDA2 = 4;
const char HAL_KEYPAD_COL0_PIN_M_MA_SPI2_CS1 = 6;
const char HAL_KEYPAD_COL0_PIN_M_DEBUGMON7 = 7;


const char HAL_KEYPAD_ROW0_PIN = 23;
const char HAL_KEYPAD_ROW0_PIN_M_GPIO = 0;
const char HAL_KEYPAD_ROW0_PIN_M_KROW0 = 1;
const char HAL_KEYPAD_ROW0_PIN_M_EINT = 2;
const char HAL_KEYPAD_ROW0_PIN_M_CLKO = 3;
const char HAL_KEYPAD_ROW0_PIN_M_U1CTS = 4;
const char HAL_KEYPAD_ROW0_PIN_M_TRACEDATA3 = 5;
const char HAL_KEYPAD_ROW0_PIN_M_MC_RST = 6;
const char HAL_KEYPAD_ROW0_PIN_M_DEBUGMON9 = 7;
const char HAL_KEYPAD_ROW0_PIN_M_JTRST_B = 8;
const char HAL_KEYPAD_ROW0_PIN_M_BTJTRSTB = 9;


const char BSP_LED1_PIN = 24;
const char BSP_LED1_PIN_M_GPIO = 0;
const char BSP_LED1_PIN_M_CMRST = 1;
const char BSP_LED1_PIN_M_LSRSTB = 2;
const char BSP_LED1_PIN_M_CLKO = 3;
const char BSP_LED1_PIN_M_EINT = 4;
const char BSP_LED1_PIN_M_GPCOUNTER_0 = 5;
const char BSP_LED1_PIN_M_JTDI = 6;
const char BSP_LED1_PIN_M_DEBUGMON10 = 7;
const char BSP_LED1_PIN_M_MC1_B_DA3 = 8;



/*Output for default variable names*/
/*@XXX_XX_PIN in gpio.cmp          */

const char BSP_CTP_SW_I2C_SCL_PIN = 0xff;
const char BSP_CTP_SW_I2C_SDA_PIN = 0xff;
const char BSP_CTP_RST_PIN = 0xff;
const char BSP_CTP_EINT_PIN = 0xff;
const char BSP_SPEAKER_EBABLE_PIN = 0xff;
const char BSP_AUXADC_ENABLE_PIN = 0xff;
const char BSP_GNSS_POWER_PIN = 0xff;
const char BSP_BIO_SENSOR_PPG_VDRV_EN = 0xff;
const char BSP_BIO_SENSOR_32K = 0xff;
const char BSP_BIO_SENSOR_RST_PORT_PIN = 0xff;
const char BSP_BIO_SENSOR_AFE_PWD_PIN = 0xff;
const char BSP_WIFI_32K_PIN = 0xff;
const char BSP_WIFI_26M_PIN = 0xff;
const char BSP_WIFI_RESET_PIN = 0xff;
const char BSP_WIFI_ENABLE_PIN = 0xff;
const char UPDATE_HOST_STATUS_PIN = 0xff;
const char QUERY_MODEM_STATUS_PIN = 0xff;
const char NOTIFY_MODEM_EXCEPTION_PIN = 0xff;
const char TRIGGER_MODEM_RESET_PIN = 0xff;
const char NOTIFY_MODEM_WAKEUP_PIN = 0xff;
const char TRIGGER_MODEM_START_PIN = 0xff;
const char TRIGGER_MODEM_WAKEUP_PIN = 0xff;
const char BSP_LED2_PIN = 0xff;
const char BSP_EINTKEY0_PIN = 0xff;
const char BSP_EINTKEY1_PIN = 0xff;
const char BSP_EINTKEY2_PIN = 0xff;





