/*
 * Generated by MTK Easy PinMux Tool Version 2.0.1 for 2523. Copyright MediaTek Inc. (C) 2015.
 * 2017-06-27 14:11:24:0916
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

const char BSP_HP_ANA_SW_PIN = 2;
const char BSP_HP_ANA_SW_PIN_M_GPIO = 0;
const char BSP_HP_ANA_SW_PIN_M_EINT = 1;
const char BSP_HP_ANA_SW_PIN_M_AUXADCIN_2 = 2;
const char BSP_HP_ANA_SW_PIN_M_U3RXD = 3;
const char BSP_HP_ANA_SW_PIN_M_U0CTS = 4;
const char BSP_HP_ANA_SW_PIN_M_MA_SPI1_A_MOSI = 5;
const char BSP_HP_ANA_SW_PIN_M_MA_EDIWS = 6;
const char BSP_HP_ANA_SW_PIN_M_MA_SPI0_A_MOSI = 7;
const char BSP_HP_ANA_SW_PIN_M_DEBUGMON13 = 8;
const char BSP_HP_ANA_SW_PIN_M_BT_BUCK_EN_HW = 9;


const char BSP_GNSS_POWER_PIN = 10;
const char BSP_GNSS_POWER_PIN_M_GPIO = 0;
const char BSP_GNSS_POWER_PIN_M_EINT = 1;
const char BSP_GNSS_POWER_PIN_M_AUXADCIN_4 = 2;
const char BSP_GNSS_POWER_PIN_M_DEBUGMON15 = 8;
const char BSP_GNSS_POWER_PIN_M_BTPRI = 9;


const char BSP_CTP_EINT_PIN = 15;
const char BSP_CTP_EINT_PIN_M_GPIO = 0;
const char BSP_CTP_EINT_PIN_M_EINT = 1;
const char BSP_CTP_EINT_PIN_M_PWM4 = 5;


const char HAL_KEYPAD_COL2_PIN = 18;
const char HAL_KEYPAD_COL2_PIN_M_GPIO = 0;
const char HAL_KEYPAD_COL2_PIN_M_KCOL2 = 1;
const char HAL_KEYPAD_COL2_PIN_M_U1RXD = 2;
const char HAL_KEYPAD_COL2_PIN_M_U3RXD = 3;
const char HAL_KEYPAD_COL2_PIN_M_TRACEDATA0 = 5;
const char HAL_KEYPAD_COL2_PIN_M_LSCE1_B1 = 6;
const char HAL_KEYPAD_COL2_PIN_M_DEBUGMON6 = 7;
const char HAL_KEYPAD_COL2_PIN_M_JTDI = 8;
const char HAL_KEYPAD_COL2_PIN_M_BTJTDI = 9;


const char HAL_KEYPAD_COL0_PIN = 20;
const char HAL_KEYPAD_COL0_PIN_M_GPIO = 0;
const char HAL_KEYPAD_COL0_PIN_M_KCOL0 = 1;
const char HAL_KEYPAD_COL0_PIN_M_GPSFSYNC = 2;
const char HAL_KEYPAD_COL0_PIN_M_U0CTS = 3;
const char HAL_KEYPAD_COL0_PIN_M_SDA2 = 4;
const char HAL_KEYPAD_COL0_PIN_M_MA_SPI2_CS1 = 6;
const char HAL_KEYPAD_COL0_PIN_M_DEBUGMON7 = 7;


const char HAL_KEYPAD_ROW1_PIN = 22;
const char HAL_KEYPAD_ROW1_PIN_M_GPIO = 0;
const char HAL_KEYPAD_ROW1_PIN_M_KROW1 = 1;
const char HAL_KEYPAD_ROW1_PIN_M_U1TXD = 2;
const char HAL_KEYPAD_ROW1_PIN_M_U3TXD = 3;
const char HAL_KEYPAD_ROW1_PIN_M_TRACEDATA2 = 5;
const char HAL_KEYPAD_ROW1_PIN_M_TRACE_SWV = 6;
const char HAL_KEYPAD_ROW1_PIN_M_DEBUGMON5 = 7;
const char HAL_KEYPAD_ROW1_PIN_M_JTDO = 8;
const char HAL_KEYPAD_ROW1_PIN_M_BTDBGIN = 9;


const char BSP_BIO_SENSOR_AFE_PWD_PIN = 24;
const char BSP_BIO_SENSOR_AFE_PWD_PIN_M_GPIO = 0;
const char BSP_BIO_SENSOR_AFE_PWD_PIN_M_CMRST = 1;
const char BSP_BIO_SENSOR_AFE_PWD_PIN_M_LSRSTB = 2;
const char BSP_BIO_SENSOR_AFE_PWD_PIN_M_CLKO = 3;
const char BSP_BIO_SENSOR_AFE_PWD_PIN_M_EINT = 4;
const char BSP_BIO_SENSOR_AFE_PWD_PIN_M_GPCOUNTER_0 = 5;
const char BSP_BIO_SENSOR_AFE_PWD_PIN_M_JTDI = 6;
const char BSP_BIO_SENSOR_AFE_PWD_PIN_M_DEBUGMON10 = 7;
const char BSP_BIO_SENSOR_AFE_PWD_PIN_M_MC1_B_DA3 = 8;


const char BSP_BIO_SENSOR_RST_PORT_PIN = 29;
const char BSP_BIO_SENSOR_RST_PORT_PIN_M_GPIO = 0;
const char BSP_BIO_SENSOR_RST_PORT_PIN_M_CMCSK = 1;
const char BSP_BIO_SENSOR_RST_PORT_PIN_M_LPTE = 2;
const char BSP_BIO_SENSOR_RST_PORT_PIN_M_CMCSD2 = 4;
const char BSP_BIO_SENSOR_RST_PORT_PIN_M_EINT = 5;
const char BSP_BIO_SENSOR_RST_PORT_PIN_M_DEBUGMON15 = 7;
const char BSP_BIO_SENSOR_RST_PORT_PIN_M_MC1_B_DA1 = 8;
const char BSP_BIO_SENSOR_RST_PORT_PIN_M_BT_RGPIO2 = 9;


const char BSP_CTP_SCL_PIN = 36;
const char BSP_CTP_SCL_PIN_M_GPIO = 0;
const char BSP_CTP_SCL_PIN_M_SCL0 = 1;
const char BSP_CTP_SCL_PIN_M_SCL1 = 2;
const char BSP_CTP_SCL_PIN_M_DEBUGMIN3 = 6;
const char BSP_CTP_SCL_PIN_M_DEBUGMON3 = 7;


const char BSP_CTP_SDA_PIN = 37;
const char BSP_CTP_SDA_PIN_M_GPIO = 0;
const char BSP_CTP_SDA_PIN_M_SDA0 = 1;
const char BSP_CTP_SDA_PIN_M_SDA1 = 2;
const char BSP_CTP_SDA_PIN_M_DEBUGMIN4 = 6;
const char BSP_CTP_SDA_PIN_M_DEBUGMON4 = 7;


const char BSP_SPEAKER_EBABLE_PIN = 45;
const char BSP_SPEAKER_EBABLE_PIN_M_GPIO = 0;
const char BSP_SPEAKER_EBABLE_PIN_M_SRCLKENAI = 1;


const char BSP_CTP_RST_PIN = 47;
const char BSP_CTP_RST_PIN_M_GPIO = 0;
const char BSP_CTP_RST_PIN_M_MA_SPI1_CS1 = 1;
const char BSP_CTP_RST_PIN_M_DEBUGMON2 = 7;



/*Output for default variable names*/
/*@XXX_XX_PIN in gpio.cmp          */

const char HAL_KEYPAD_COL1_PIN = 0xff;
const char HAL_KEYPAD_ROW2_PIN = 0xff;
const char HAL_KEYPAD_ROW0_PIN = 0xff;
const char BSP_AUXADC_ENABLE_PIN = 0xff;




