/*
 * Generated by MTK Easy PinMux Tool Version 2.0.1 for 2523. Copyright MediaTek Inc. (C) 2015.
 * 2016-10-24 19:59:28:0643
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/

const unsigned char HAL_MSDC_EINT = 7;
const unsigned char HAL_ACCDET_EINT = 8;
const unsigned char BSP_GNSS_EINT = 10;
const unsigned char BSP_CTP_EINT = 13;
const unsigned char BSP_WIFI_EINT = 0xff;



