IC_CONFIG = mt2523
BOARD_CONFIG = mt2523_hdk

# combo sensor of accelerometer and gyroscope
MTK_SENSOR_ACCELEROMETER_USE = BMA255
#MTK_SENSOR_ACCELEROMETER_USE = BMI160

MTK_SENSOR_SUBSYS_SINGLE_TASK = y
BMA255_USE_POLLING = y