/*
 * Generated by MTK Easy PinMux Tool Version 1.0.3 for 2523. Copyright MediaTek Inc. (C) 2015.
 * Fri Apr 22 08:52:07 2016
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/


const char BSP_CTP_RST_PIN = 0;
const char BSP_CTP_RST_PIN_M_GPIO = 0;
const char BSP_CTP_RST_PIN_M_EINT = 1;
const char BSP_CTP_RST_PIN_M_AUXADCIN_0 = 2;
const char BSP_CTP_RST_PIN_M_U2RXD = 3;
const char BSP_CTP_RST_PIN_M_PWM0 = 4;
const char BSP_CTP_RST_PIN_M_MA_SPI1_A_CS = 5;
const char BSP_CTP_RST_PIN_M_MA_EDIDO = 6;
const char BSP_CTP_RST_PIN_M_MA_SPI0_A_CS = 7;
const char BSP_CTP_RST_PIN_M_DEBUGMON11 = 8;
const char BSP_CTP_RST_PIN_M_BTJTDO = 9;


const char BSP_GNSS_POWER_PIN = 10;
const char BSP_GNSS_POWER_PIN_M_GPIO = 0;
const char BSP_GNSS_POWER_PIN_M_EINT = 1;
const char BSP_GNSS_POWER_PIN_M_AUXADCIN_4 = 2;
const char BSP_GNSS_POWER_PIN_M_DEBUGMON15 = 8;
const char BSP_GNSS_POWER_PIN_M_BTPRI = 9;


const char BSP_CTP_EINT_PIN = 15;
const char BSP_CTP_EINT_PIN_M_GPIO = 0;
const char BSP_CTP_EINT_PIN_M_EINT = 1;
const char BSP_CTP_EINT_PIN_M_PWM4 = 5;


const char BSP_SPEAKER_EBABLE_PIN = 18;
const char BSP_SPEAKER_EBABLE_PIN_M_GPIO = 0;
const char BSP_SPEAKER_EBABLE_PIN_M_KCOL2 = 1;
const char BSP_SPEAKER_EBABLE_PIN_M_U1RXD = 2;
const char BSP_SPEAKER_EBABLE_PIN_M_U3RXD = 3;
const char BSP_SPEAKER_EBABLE_PIN_M_TRACEDATA0 = 5;
const char BSP_SPEAKER_EBABLE_PIN_M_LSCE1_B1 = 6;
const char BSP_SPEAKER_EBABLE_PIN_M_DEBUGMON6 = 7;
const char BSP_SPEAKER_EBABLE_PIN_M_JTDI = 8;
const char BSP_SPEAKER_EBABLE_PIN_M_BTJTDI = 9;


const char gpio_20_strapping_pin = 20;
const char gpio_20_strapping_pin_M_GPIO = 0;
const char gpio_20_strapping_pin_M_KCOL0 = 1;
const char gpio_20_strapping_pin_M_GPSFSYNC = 2;
const char gpio_20_strapping_pin_M_U0CTS = 3;
const char gpio_20_strapping_pin_M_SDA2 = 4;
const char gpio_20_strapping_pin_M_MA_SPI2_CS1 = 6;
const char gpio_20_strapping_pin_M_DEBUGMON7 = 7;


const char BSP_CTP_SCL_PIN = 36;
const char BSP_CTP_SCL_PIN_M_GPIO = 0;
const char BSP_CTP_SCL_PIN_M_SCL0 = 1;
const char BSP_CTP_SCL_PIN_M_SCL1 = 2;
const char BSP_CTP_SCL_PIN_M_DEBUGMIN3 = 6;
const char BSP_CTP_SCL_PIN_M_DEBUGMON3 = 7;


const char BSP_CTP_SDA_PIN = 37;
const char BSP_CTP_SDA_PIN_M_GPIO = 0;
const char BSP_CTP_SDA_PIN_M_SDA0 = 1;
const char BSP_CTP_SDA_PIN_M_SDA1 = 2;
const char BSP_CTP_SDA_PIN_M_DEBUGMIN4 = 6;
const char BSP_CTP_SDA_PIN_M_DEBUGMON4 = 7;


const char gpio_40_strapping_pin = 40;
const char gpio_40_strapping_pin_M_GPIO = 0;
const char gpio_40_strapping_pin_M_LSCK0 = 1;
const char gpio_40_strapping_pin_M_CMPDN = 3;
const char gpio_40_strapping_pin_M_SFSHOLD = 5;
const char gpio_40_strapping_pin_M_DEBUGMON10 = 7;
const char gpio_40_strapping_pin_M_MA_SPI2_B_SCK = 9;


const char gpio_44_strapping_pin = 44;
const char gpio_44_strapping_pin_M_GPIO = 0;
const char gpio_44_strapping_pin_M_LSCE1_B1 = 1;
const char gpio_44_strapping_pin_M_DISP_PWM = 2;
const char gpio_44_strapping_pin_M_DEBUGMON0 = 7;
const char gpio_44_strapping_pin_M_DEBUGMON6 = 8;


const char gpio_46_strapping_pin = 46;
const char gpio_46_strapping_pin_M_GPIO = 0;
const char gpio_46_strapping_pin_M_MA_SPI0_CS1 = 1;
const char gpio_46_strapping_pin_M_DEBUGMON1 = 7;


const char gpio_47_strapping_pin = 47;
const char gpio_47_strapping_pin_M_GPIO = 0;
const char gpio_47_strapping_pin_M_MA_SPI1_CS1 = 1;
const char gpio_47_strapping_pin_M_DEBUGMON2 = 7;


const char gpio_48_strapping_pin = 48;
const char gpio_48_strapping_pin_M_GPIO = 0;
const char gpio_48_strapping_pin_M_MA_SPI3_CS1 = 1;
const char gpio_48_strapping_pin_M_DEBUGMON5 = 7;



/*Output for default variable names*/
/*@XXX_XX_PIN in gpio.cmp          */

const char HAL_KEYPAD_COL2_PIN = 0xff;
const char HAL_KEYPAD_COL1_PIN = 0xff;
const char HAL_KEYPAD_COL0_PIN = 0xff;
const char HAL_KEYPAD_ROW2_PIN = 0xff;
const char HAL_KEYPAD_ROW1_PIN = 0xff;
const char HAL_KEYPAD_ROW0_PIN = 0xff;
const char BSP_AUXADC_ENABLE_PIN = 0xff;
const char BSP_BIO_SENSOR_PPG_VDRV_EN = 0xff;
const char BSP_BIO_SENSOR_32K = 0xff;
const char BSP_BIO_SENSOR_RST_PORT_PIN = 0xff;
const char BSP_BIO_SENSOR_AFE_PWD_PIN = 0xff;




