/*
 * Generated by MTK Easy PinMux Tool Version 1.0.3 for 2523. Copyright MediaTek Inc. (C) 2015.
 * Fri Apr 22 08:52:07 2016
 * Do Not Modify the File.
 */

/*****************************************************************************
*
* Filename:
* ---------
*    ***.*
*
* Project:
* --------
*
* Description:
* ------------
*
* Author:
* -------
*
*============================================================================
****************************************************************************/


const unsigned char HAL_ACCDET_EINT = 1;
const unsigned char BSP_GNSS_EINT = 10;
const unsigned char BSP_CTP_EINT = 13;
const unsigned char HAL_MSDC_EINT = 18;




